services:
  api1:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5187:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  api2:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5188:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  api3:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5189:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  client:
    build:
      context: ./client/myStudents
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Access UI at localhost:5173
    depends_on:
      - api1
      - api2
      - api3
    volumes:
      - ./client/myStudents/src:/app/src
